name: "Feature to Develop branch Pull Request"

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: ["develop"]

permissions:
  contents: read

env:
  APP_NAME: "472-fe-cicd"

jobs:
  build_application:
    name: "Build Dockerfile"
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"
      - name: "Build"
        run: docker build -t 472-fe-cicd -f ./docker/dev.Dockerfile .
